version: '28.0.4'

services:
  app:
    build: .
    ports:
      - "8001:8001"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    volumes:
      - .:/usr/src/string.js
    command: npm start

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
